### ISSUE TITLE
Jaxb-Facets @MaxOccurs generated XML Schema validation not working

### ISSUE THREAD

**Issue by santhoshkrv** [whummer/jaxb-facets#26]
In Jaxb-Facets 
Given @MaxOccurs(2) for java collection datatype

@MaxOccurs(2)
List<String> testList;

But if we give more than 2 data in SOAP UI for testing, operation runs successfully without returning a fault message "Maximum 2 data can be given"

No Schema Validation happening

**Comment by whummer** [comment]
This is true, JAXB-Facets only generates schema documents, but does not enforce the schema restrictions. What you are asking for does not directly have to do with JAXB - it would have to be implemented in the JAX-WS Web service stack implementation. It should be easy to integrate this as a handler in JAXWS, using the schema validation facilities of JAXB.

Closing this issue, but feel free to update us here on the progress, in case you find out more. Thanks.

**Comment by pellcorp** [comment]
https://web-gmazza.rhcloud.com/blog/entry/soap-xml-schema-validation
