### ISSUE TITLE
Which license

### ISSUE THREAD

**Issue by timogruetter** [whummer/jaxb-facets#27]
Hi whummer,

it is not really an issue, but can you tell me under which license the software is published?
Are we allowed to use it anywhere?

**Comment by pellcorp** [comment]
Its same license as jaxb itself I believe

**Comment by timogruetter** [comment]
Then it should be "CDDL v1.1 and GPL v2" as mentioned here (https://jaxb.java.net). But it would be nice if it is mentioned somewhere in the project, otherwise wie cannot usw it

**Comment by pellcorp** [comment]
agreed - we need to push a LICENSE file to the root of the project.

**Comment by whummer** [comment]
Fixed in d2db280f16add0ba44685803b07249f1683f1049
